### ISSUE TITLE
No Info(Vue) Tabe when docs not in panel

### ISSUE THREAD

**Issue by psi-4ward** [pocka/storybook-addon-vue-info#101]
When displaying the documentation within preview pane we can remove the `Info(Vue)` Tab from 
the addons panel cause it's empty.

https://github.com/pocka/storybook-addon-vue-info/blob/953da5518981eda113b99cea59f32e35349cf7f2/src/register.tsx#L80

what do you think?

**Comment by pocka** [comment]
If you never use `Info(Vue)` tab in the whole stories, remove this line from `.storybook/addon.js`

```js
// .storybook/addons.js
import 'storybook-addon-vue-info/lib/register'
```

AFAIK, there is no way to remove (or hide) addon tabs in runtime.

**Comment by psi-4ward** [comment]
Thx, this solves the issue!
