### ISSUE TITLE
Feature Request: SlotDescriptions (just like propDescriptions)

### ISSUE THREAD

**Issue by Xayer** [pocka/storybook-addon-vue-info#106]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Same functionality as propDescriptions, but for slots. eg. slotDescriptions.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by pocka** [comment]
I opened a [PR](https://github.com/pocka/storybook-addon-vue-info/pull/111) that adds `description` option for stories.
What do you think about it? I'd like to hear opinions from who uses `propsDescription`!

**Comment by Xayer** [comment]
@pocka I realized that I could use code comments on the props, and achieve the same result. How would one go about doing so on slots?

**Comment by pocka** [comment]
Yeah, you can add description for slots by using slot comments with vue-docgen-api.
I'll merge the PR so to non docgen-users can do this then add documentation about slot comments.

**Comment by pocka** [comment]
Released in v1.3.0
