### ISSUE TITLE
Throws an error if props was specified as an array and useDocgen option is false

### ISSUE THREAD

**Issue by femioladeji** [pocka/storybook-addon-vue-info#107]
**Describe the bug**
When props for a component is specified as an array of string when the useDocgen option is set to false, it tries to get the default value [here](https://github.com/pocka/storybook-addon-vue-info/blob/faab87838fc270bc58122c4279c01ba5122dd400/src/extract/getProps.ts#L55) in the `getProps` method by using the `in` operator on a string thereby throwing an error.

**Expected behavior**
It should just return an empty string as the default value

**Versions**

- `storybook-addon-vue-info`: ^1.2.1
- `@storybook/vue`: ^5.1.9

**Comment by pocka** [comment]
Fixed in [v1.2.2](https://github.com/pocka/storybook-addon-vue-info/blob/master/CHANGELOG.md#122---2019-07-26)
