### ISSUE TITLE
Broken knobs addon

### ISSUE THREAD

**Issue by przspa** [pocka/storybook-addon-vue-info#116]
**Describe the bug**
https://storybook-addon-vue-info.netlify.com/?path=/story/compatibilities-storybook-addon-knobs--panel like here. when I use knobs forceRerendered was triggered just one time, after that I cant change knobs

**To Reproduce**

1. Go to https://storybook-addon-vue-info.netlify.com/?path=/story/compatibilities-storybook-addon-knobs--panel
2. Change knobs once
3. Change knobs second time

**Expected behavior**
Knobs should be changed 

**Screenshots**

**Versions**

- `storybook-addon-vue-info`: 1.3.2
- `@storybook/vue`: 5.2.4

**Additional context**

**Comment by pocka** [comment]
It doesn't happen with `@storybook/vue@5.1.11`. Seems like a bug on SB?
