### ISSUE TITLE
Support mixin

### ISSUE THREAD

**Issue by beyzacaliskan** [pocka/storybook-addon-vue-info#117]
When a component is created using mixin, I can not see the props that come from mixin. I created checkbox component using selectable mixin and added indeterminate props.

```javascript
import Selectable from '../../components/selectable'

export default {
  name: 'my-checkbox',

  mixins: [
    Selectable
  ],
  props: {
    indeterminate: Boolean,
  }
```
When I write a story for checkbox component I didn't see props of selectable component. I saw only indeterminate prop in the props table. How can I show props come from selectable component?

**Comment by pocka** [comment]
@beyzacaliskan Please use issue templates.

The addon only shows props/events/methods which defined in mixins when you use [the docgen loader](https://github.com/pocka/storybook-addon-vue-info#getting-started). Otherwise, the addon displays props only come from the component itself.
