### ISSUE TITLE
Issue when using template literals

### ISSUE THREAD

**Issue by ads1018** [pocka/storybook-addon-vue-info#12]
This throws an error `No match components registered: utc-btn`

```html
storiesOf('UtcBtn', module)
  .addDecorator(VueInfoAddon)
  .add('Default', () => ({
    template: `
      <UtcBtn>
        Default
      </UtcBtn>
    `
  }))
```

However, when everything in the template literal is on the same line the issue goes away:
```html
storiesOf('UtcBtn', module)
  .addDecorator(VueInfoAddon)
  .add('Default', () => ({
    template: `<UtcBtn>Default</UtcBtn>`
  }))
```

Any idea what's going on here?

**Comment by pocka** [comment]
It's template parsing bug (<https://github.com/pocka/storybook-addon-vue-info/blob/master/src/utils/getOutermostTagName.ts#L8>).

#9 

I'll open quick fix soon...

**Comment by pocka** [comment]
@ads1018 I've just published patched version to npm. Thank you for reporting!

**Comment by ads1018** [comment]
Fantastic! Thanks for letting me know!
