### ISSUE TITLE
Props name can show with '-' connection ?

### ISSUE THREAD

**Issue by zhnoah** [pocka/storybook-addon-vue-info#122]
**Is your feature request related to a problem? Please describe.**

.vue file
```js
...
props: {
  addonTooltip: String
}
...
```

info panel

NAME|TYPE|DEFAULT|DESCRIPTION
--|:--:|--:|--:
addon-tooltip|string| | 

**Describe the solution you'd like**

Can an option be implemented?

```js
setDefaults({
    useHyphen: true
});
```
Feasible?

**Describe alternatives you've considered**

**Additional context**

**Comment by pocka** [comment]
Yes, and we should implement it!
