### ISSUE TITLE
'Failed to get default value' with Function type prop and default

### ISSUE THREAD

**Issue by jackysee** [pocka/storybook-addon-vue-info#126]
For prop like this:
```
getLabel: { type: Function, default: item => item.desp }
```
The addon would try to run the default function and result in prop table:

![image](https://user-images.githubusercontent.com/30516/73624446-c4820b00-467b-11ea-9413-f788b08b859e.png)

while it should print the function implementation itself.

**Versions**

- `storybook-addon-vue-info`: 1.4.1
- `@storybook/vue`: 5.3.10

**Comment by pocka** [comment]
Fixed in [v1.4.2](https://github.com/pocka/storybook-addon-vue-info/releases/tag/v1.4.2).

Please use an issue template.
