### ISSUE TITLE
Array type props displayed as unknown

### ISSUE THREAD

**Issue by pocka** [pocka/storybook-addon-vue-info#16]
Props with `type: Array` are displayed as Type=unknown in the props table.
Additionally, when it has `default` which is factory function that returns default value, there are function's source code in the props table...

![screenshot-2018-1-31 storybook](https://user-images.githubusercontent.com/13316015/35602546-2ced5916-067c-11e8-8322-95e32c82a6f2.png)

**Comment by dherian** [comment]
Same when props type is an Object

**Comment by pocka** [comment]
Published patched version(0.1.8)
