### ISSUE TITLE
Unkown props type

### ISSUE THREAD

**Issue by gongzza** [pocka/storybook-addon-vue-info#3]
Hi,

i got 'Unkown' props type

i defined props like this:

```
props: {
  disabled: Boolean
}
```

i guess modify [src/getPropsInfoList.ts#L22](https://github.com/pocka/storybook-addon-vue-info/blob/master/src/getPropsInfoList.ts#L22) like below:

```
- type: constructorToString(prop.type),
+ type: constructorToString(prop.type || prop)
```

**Comment by pocka** [comment]
Thank you for reporting! I'll write fix for it.

**Comment by pocka** [comment]
Merged patch and Published latest version to NPM.
