### ISSUE TITLE
Add linting for addon codebase

### ISSUE THREAD

**Issue by pocka** [pocka/storybook-addon-vue-info#35]
* Add linting for `src/**/*.ts` and `src/**/*.vue` on `npm run lint`
* Lint on CI

**Comment by zhaozhe0831** [comment]
@pocka 
like formate code? auto change line?

**Comment by pocka** [comment]
@zhaozhe0831 
Both formatting and linting (enforce best practice).

current plan:
* Format code with [prettier](https://github.com/prettier/prettier) before commit (using [lint-staged and husky](https://prettier.io/docs/en/precommit.html)) 
* Check code with tslint and eslint (for `.vue` files) on `npm run lint` or similar
* Check code with tslint and eslint on CI

**Comment by zhaozhe0831** [comment]
About storybook, how about like this?

**Comment by pocka** [comment]
@zhaozhe0831 
Sorry for my ambiguous description :pensive:
This issue means "Add linting process for developing this library", not "Lint story source code on runtime".
Linting story source or component source code should be done by users.

**Comment by zhaozhe0831** [comment]
OK, I know this.

But it's too hard to format template in `*.js`.

I am thinking about how I can format template in `*.vue`.
I think that It means use `*.vue` as  `*.stories.js`.
I want to resolve this problem. 
Maybe I want to make storybook-to-vue easier to use.

I know this problem is not this git's issue.

Thank you.

**Comment by pocka** [comment]
Ah, I see :sunglasses:

AFAIK, there are no tools that format component's inline template.
I don't know we can treat `*.vue` as story source now, but it may requires core support of storybook/vue.

If your story does not have any state, methods, computed property, etc..., you can use JSX that can be formatted by formatter since `storybook-addon-vue-info@0.4.2` :+1:

**Comment by zhaozhe0831** [comment]
You mean Template(or String) can't be formatted by formatter, but JSX can be formatted ?
I didn't use JSX before, because  I wouldn't like to type dom in js.
But I'll try it maybe this time.

**Comment by zhaozhe0831** [comment]
```js
// index.stories.js
import { storiesOf } from '@storybook/vue';
import { withKnobs, text, boolean, number } from '@storybook/addon-knobs';

import DemoButton from './stories/button.stories.vue';

const vueData = {
    props: { 
       text,
       boolean,
       number
    }
};

storiesOf('Button', module)
  .addDecorator(withKnobs)
  .add('with text', () => ({
      render: (h) => h(DemoButton, vueData)
  }));
```

```vue
// button.stories.vue
<template>
    <base-button :class="className">{{ label }}</base-button>
</template>

<script>
import BaseButton from '@/src/components/Button';

export default {
    data() {
        return {
            className: this.text('class', 'btn'),
            label:  this.text('text', 'Hello 123')
        }
    },

    props:['text', 'boolean', 'number'],

    components:{
        BaseButton
    }
}
</script>
```

I try like this, it's useful. Knos is normal running.

What do you think of this way？

**Comment by pocka** [comment]
@zhaozhe0831 Looks simple and clean :+1: 

But, to archive this way, we need to add option like `storySource: string | VueComponent` and complete support for "render function to JSX".

```js
// index.stories.js
import { storiesOf } from '@storybook/vue';
import { withKnobs, text, boolean, number } from '@storybook/addon-knobs';
import { withInfo } from 'storybook-addon-vue-info'

import DemoButton from './stories/button.stories.vue';

import BaseButton from '@/src/components/Button';

const vueData = {
    props: { 
       text,
       boolean,
       number
    }
};

storiesOf('Button', module)
  .addDecorator(withKnobs)
  .add('with text', withInfo({
    storySource: DemoButton,
    propTables: [BaseButton]
  })(() => ({
      render: (h) => h(DemoButton, vueData)
  })));
```

This addon aims to provide a Vue.js version of official info addon, not an enriched version.
Since this feature is not implemented in official addon and is not a necessary one, I think we should not add this.

So, my answer for "How can I format or lint story source?" is "You can't. If your story component is simple, consider using JSX".

**Comment by zhaozhe0831** [comment]
I'm not good at English.
I understand you a little.

You mean it's not necessary like this.
```js
storiesOf('Button', module)
  .addDecorator(withKnobs)
  .add('with text', withInfo({
    storySource: DemoButton, // it's not necessary ?
    propTables: [BaseButton]
  })(() => ({
      render: (h) => h(DemoButton, vueData)
  })));
```

**Comment by pocka** [comment]
@zhaozhe0831 
No, `storySource` is necessary.
If we don't specify it, we get following story source:

```jsx
;<DemoButton text={text} boolean={boolean} number={number}/>
```

If we add `storySource: DemoButton`, we can get following story source:

```jsx
;<base-button class={className}>{ label }</base-button>
```

**Comment by zhaozhe0831** [comment]
OK，but `storySource` isn't exist now ？
If realized this function ，the addon must be add a option `storySource` ?
