### ISSUE TITLE
Support a render function?

### ISSUE THREAD

**Issue by Aaron-Pool** [pocka/storybook-addon-vue-info#36]
I know this is substantially more complicated to display "usage" for than a template string, but is there any chance we could get support for a render function, like the storybook official addon allows?

**Comment by pocka** [comment]
Yes, it should be displayed! If it's difficult (or unable) to implement, showing "not supported" message without `` `template` must be on component options, but got undefined. `` is needed.

**Comment by Aaron-Pool** [comment]
Cool, if I can help at all, let me know! Thanks for all the great work on this, by the way--I'm on a Vue project that is very seriously considering storybook for our shared pattern library, and before we found this one of our big concerns was that the `info` addon added so much functionality, but only worked with React. So, thanks for solving that!

**Comment by pocka** [comment]
I've added partial support for render function at v0.4.2 with [some limitations](#38 ).
Waiting for Vue.js support for custom renderer or vue-docgen integration in storybook/vue ...

**Comment by Aaron-Pool** [comment]
Great! Thanks @pocka !

**Comment by pocka** [comment]
I'm closing this issue in favor of the official Docs addon.

That addon shows the whole story code as-is, so I think it displays render function without any problem.
