### ISSUE TITLE
overflowing usage text

### ISSUE THREAD

**Issue by gongzza** [pocka/storybook-addon-vue-info#4]
i used a long text into template

and i got the horizontal scroll of InfoView.

i think the text should be in the box of the usage.

i guess modify [InfoView.vue#L65](https://github.com/pocka/storybook-addon-vue-info/blob/master/src/components/InfoView.vue#L65) like this:
```
.code {
  overflow: auto;
}
```

**Comment by pocka** [comment]
I'v reproduce the issue and confirmed you're suggested code works well! (send PR soon)

---

![screenshot-2017-12-7 storybook](https://user-images.githubusercontent.com/13316015/33705710-adf9d210-db74-11e7-8149-d9bed0dd9c84.png)

---

Applied `overflow: auto`

![screenshot-2017-12-7 storybook 1](https://user-images.githubusercontent.com/13316015/33705740-c4c9f146-db74-11e7-8dcd-c2fd6928b2ba.png)

**Comment by pocka** [comment]
Updated version and Published to NPM
