### ISSUE TITLE
JS not being transpiled on stories with the addon, including the example application

### ISSUE THREAD

**Issue by stabback** [pocka/storybook-addon-vue-info#48]
## Describe the bug
JS in component `<script>` tags that are used by stories with this addon is not being transpiled by babel.  The JS is being output straight to the browser, breaking storybook on IE11 or on any browser which does not support the JS written in the component.

This is true in the example application once babel-preset-env is enabled.  If I have enabled it in a way that was not intended, I'd be happy to correct.

## To Reproduce

Note yarn is used, the results are the same with npm.

1. Clone this repository
2. Install the example app.  Note I had to change package.json to link to the app itself, I was unable to install with `yarn` due to the dependency being a file link. 
3. Add IE11 support - `yarn add babel-preset-env`
4. Enable IE11 support - modify `.babelrc` to:
```
{
    "plugins": [
      "transform-vue-jsx"
    ],
    "presets": [
      "env"
    ]
}
```
5. Start storybook with `yarn storybook`
6. Open http://localhost:8080 in chrome and IE11
7. Observe that chrome runs fine while IE11 is tripped up by the fat arrow functions in the example stories
8. Edit `stories/index.js` to remove all references to storybook-addon-vue-info.  Remove the plugin from `.storybook/config.js`.  I've included my modified versions in the additional context section below to help with this, it's a bit of a hunt.
9. Repeat 5 and 6 above to start the example app
10. Observe that both Chrome and IE11 run the app fine.  The fat arrow functions are properly transpiled.

## Expected behavior
JS within the components are transpiled with babel like other JS

## Desktop
Mac chrome (works) - whatsmybrowser.org/b/LPSGV93
Windows 10 chrome (works) - https://www.whatsmybrowser.org/37WYQNM
Windows 10 IE11 (does not work) - https://www.whatsmybrowser.org/97DBL37

## Additional content

Modified files to remove storybook-addon-vue-info for testing purposes:

### stories/index.js
```js
import { storiesOf } from '@storybook/vue'

import BaseBlank from '../src/components/BaseBlank.vue'
import BaseButton from '../src/components/BaseButton.vue'

import NumberList from '../src/components/NumberList.vue'
import RenderFnComponent from '../src/components/RenderFnComponent'

storiesOf('BaseButton', module)
  .add('global component', () => ({
    template: '<base-button type="primary" label="global"/>'
  }))
  .add('local component', () => ({
    components: {
      LocalButton: BaseButton
    },
    template: '<local-button :disabled="true" label="local"/>'
  }))
  .add('long long template', () => ({
    template:
      '<base-button type="primary" disabled label="Storybook is a development environment for UI components. It allows you to browse a component library, view the different states of each component, and interactively develop and test components."/>'
  }))
  .add('multiline template', () => ({
    template: `
      <base-button label="You can also use multiline template!">
      </base-button>
    `
  }))

storiesOf('Multiple components props', module)
  .add(
    'Shows multiple components props',
    () => ({
      components: { LocalButton: BaseButton, BaseBlank },
      template: `
    <div>
      <base-button label="I'm <base-button>"/>
      <base-blank/>
      <local-button label="I'm <local-button>"/>
    </div>
    `
    })
  )
  .add(
    'Specify which components will be shown',
    () => ({
      components: { LocalButton: BaseButton, BaseBlank },
      template: `
    <div>
      <base-button label="I'm <base-button>"/>
      <base-blank/>
      <local-button label="I'm <local-button>"/>
    </div>
    `
    })
  )

storiesOf('withInfo API', module)
  .add(
    'withInfo/1',
    () => ({
      template: '<base-button label="You can use withInfo API"/>'
  }))
    
  .add(
    'set .header=false',
    () => ({
      template: '<base-button label="No header info!"/>'
    })
  )
  .add(
    'set .source=false',
    () => ({
      template: '<base-button label="Without source"/>'
    })
  )
  .add(
    'set .style',
    () => ({
      template: '<base-button label="funny styled info"/>'
    })
  )
  .add(
    'set .summary',
    () => ({
      template: '<base-button label="awesome button"/>'
    })
  )
  .add(
    'pass summary strings to options',
    () => ({
      template: '<base-button label="My Awesome Button!"/>'
    })
  )
  .add(
    'Markdown summary',
    () => ({
      template: '<base-button label="See description"/>'
    })
  )
  .add(
    'JSX story',
    () => ({
      render(h) {
        return <base-button label="written in JSX" />
      }
    })
  )
  .add(
    'JSX story(2)',
    () => ({
      render(h) {
        return <BaseButton style={{ fontSize: '2em' }} label="Okay." />
      }
    })
  )

storiesOf('BaseBlank', module)
  .add('blank', () => ({
    components: { BaseBlank },
    template: '<base-blank/>'
  }))

storiesOf('NumberList', module)
  .add('A prop with `type: Array`', () => ({
    components: { NumberList },
    template: '<number-list :numbers="[3, 4, 5]"/>'
  }))

storiesOf('RenderFnComponent', module).add(
  'Works with non-SFC',
  () => ({
    render(h) {
      return <RenderFnComponent name="Vue" />
    }
  })
)
```

### .storybook/config.js
```js
import { configure } from '@storybook/vue'

import Vue from 'vue'

import BaseButton from '../src/components/BaseButton.vue'

Vue.component('base-button', BaseButton)

function loadStories() {
  require('../stories')
}

configure(loadStories, module)
```

**Comment by pocka** [comment]
@stabback 
Thanks for reporting bug :)

I guess the problem exists in bundled code of this addon itself (not in stories or components).
In compiling process, Rollup transpile addon code with `rollup-plugin-typescript2` and `rollup-plugin-vue`, but there is no `rollup-plugin-babel` which transpile JS in `.vue` file ([`rollup.config.js`](https://github.com/pocka/storybook-addon-vue-info/blob/465d25d1a90292321780040384a02d86b1bd6247/rollup.config.js)). So JS in [our preview components](https://github.com/pocka/storybook-addon-vue-info/blob/465d25d1a90292321780040384a02d86b1bd6247/src/components/InfoHeader.vue) will not transpiled.

And, yes, we should support IE11  :smirk:

**Comment by stabback** [comment]
@pocka Amazing!  Easily the quickest bug report I've seen fixed.
