### ISSUE TITLE
Hide Props section if there is none in the component

### ISSUE THREAD

**Issue by miguelRivero** [pocka/storybook-addon-vue-info#57]
**Is your feature request related to a problem? Please describe.**
I've tried to use propTablesExclude for this with vue, but it doesn't work

**Describe the solution you'd like**
Hide Props section if there is none in the component, so it doesnt show the props table header and no content

**Describe alternatives you've considered**
Pass a boolean to hide Pros in settings, or do it automatically

**Comment by pocka** [comment]
> I've tried to use propTablesExclude for this with vue, but it doesn't work

Yes, `propTablesExclude` is not implemented  :persevere:

IMO, implementing `propTablesExclude` is better and straightfoward than adding custom option to hide props section.

**Comment by pocka** [comment]
@miguelRivero Does #60 solve the problem?

**Comment by miguelRivero** [comment]
> @miguelRivero Does #60 solve the problem?

Not for me.

**Comment by pocka** [comment]
@miguelRivero 
Is your problem "Having an error `context is undefined` when use storybook-addon-vue-info" ? If so, please fill an another issue.
I tested `propTablesExclude` option and confirmed it works. I think this issue (`Hide Props section if there is none in the component`) is now resolved.

**Comment by pocka** [comment]
In v1.0.0-alpha, the addon now hides prop tables when the component does not have any props.
