### ISSUE TITLE
Let's collaberate!

### ISSUE THREAD

**Issue by ndelangen** [pocka/storybook-addon-vue-info#58]
Hey @pocka !

This is a great addon, thank you so much for creating this!

Would you care working together on a docs-view mode in the code of storybook?

Essentially the react-info and this addon will render docs about a component as a wrapper inside the iframe.
This is problematic long term for tools that integrate with storybook. So taking this documentation into the manager frame instead is something I'm currently working on.

Highly value your ideas and input, want to work together and chat on our discord? https://discord.gg/sMFvFsG

**Comment by pocka** [comment]
> Essentially the react-info and this addon will render docs about a component as a wrapper inside the iframe.
This is problematic long term for tools that integrate with storybook. So taking this documentation into the manager frame instead is something I'm currently working on.

Great!
It would make us easy to add framework support for @storybook/addon-info if this feature comes.
I'd like to help as much as I can :wink: 

Related #42

**Comment by pocka** [comment]
Docs-mode shipped in v5.2.0 🎉
