### ISSUE TITLE
Props are not inherited when extending a component

### ISSUE THREAD

**Issue by Rinux55** [pocka/storybook-addon-vue-info#59]
**Describe the bug**
When you extend a vue component, the parent's props are not displayed in the propstable.

parent-component

    export default {
        props: {
            foo: String
        }
    }

child-component

    import parentComponent from './parent-component'

    export default {
       extends: parentComponent
    }

When I write a story for child-component I expect the property `foo` of the parent-component to be visible in the info props table - which it is not.

**Comment by pocka** [comment]
This addon does not support mixin or `extends`. You can add parent's props by using `propTables` option.

**Comment by rodneyrehm** [comment]
I'm running into the same problem…

> This addon does not support mixin or extends.

Is this due to technical limitations or simply a "haven't gotten around to implementing this yet"?

**Comment by pocka** [comment]
Now we can display inherited props by using [docgen loader](https://github.com/pocka/storybook-addon-vue-info/tree/release/v1.0#setup-docgen-loader). Fixed version: 1.0.0-alpha.3
