### ISSUE TITLE
Add documentation for events and slots

### ISSUE THREAD

**Issue by pribilinskiy** [pocka/storybook-addon-vue-info#61]
It would be nice to have a tabbed view for all input and output of a component, not just props.

**Describe alternatives you've considered**
See [Vuetify docs](https://vuetifyjs.com/en/components/navigation-drawers) for inspiration

![image](https://user-images.githubusercontent.com/3078595/50896725-a1ead780-1412-11e9-929e-6616dd27cd85.png)

**Comment by blaadje** [comment]
Agreed 👍

**Comment by pocka** [comment]
Implemented at v1.0.0-alpha.6.

You must configure docgen-loader for vue-docgen-api integration. For more detail, see [README on v1.0.0](https://github.com/pocka/storybook-addon-vue-info/tree/b55486446838a25e023cbb2cbac8760895279a37#setup-docgen-loader).
CAUTION: This loader is still in an experiment and may cause bug/crush.

Live demo:
https://deploy-preview-66--storybook-addon-vue-info.netlify.com/?selectedKind=Examples%2FBasic%20usage&selectedStory=Simple%20example&full=0&addons=1&stories=1&panelRight=0
