### ISSUE TITLE
Planned deprecation

### ISSUE THREAD

**Issue by pocka** [pocka/storybook-addon-vue-info#65]
# Current status (Update: Nov 14)

Docs-Mode is now available in [Storybook v5.2.0](https://github.com/storybookjs/storybook/tree/master/addons/docs)!
If you want well-integrated, SB native looks, and easy to use documentation, please try it!
(documentation for events and slots are available from v5.3.0)

- [Storybook Docs: Technical Preview(Guide docs)](https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing)
- More on #docs-mode channel on [Storybook Discord](https://discord.gg/sMFvFsG)

---

This is a remind issue.

It seems that Storybook team plans to add docs-view mode, which has almost the same features to info addon.
I think when it comes this addon is no longer necessary. It should go to maintenance mode then.

**Comment by pribilinskiy** [comment]
@pocka any new about docs-view mode?

**Comment by pocka** [comment]
@pribilinskiy Nothing new. At least they probably will not ship docs-view mode with v5.

**Comment by pocka** [comment]
FYI There is the #docs-mode channel in Storybook Discord.

**Comment by shilman** [comment]
@pocka I'm prototyping it now that v5 is shipped, and will be requesting feedback once it's in basic shape. Would you be available to give feedback?

Or even help develop it? I'm making it view layer independent, like the rest of storybook, but will need help on each view layer. As you can imagine, I'm looking at this addon to prototype Vue, and am even using your docgen-loader unmodified.

**Comment by pocka** [comment]
@shilman 
Thank you for pinging. I'm looking forward to it!

**Comment by pocka** [comment]
I put the link to the Docs-mode on top of the README.

And noticed storybook depends on this package... maybe for the docgen loader?
Probably I need to separate the loader before deprecating this addon...

**Comment by pocka** [comment]
Deprecated.

I'll deprecate the npm package once SB6 was released.
