### ISSUE TITLE
Mixin props are not imported

### ISSUE THREAD

**Issue by BB101** [pocka/storybook-addon-vue-info#76]
**Describe the bug**
When using a mixin that declares props, storybook-addon-vue-info ignores them.

**To Reproduce**
mixin:
```
export default {
  props: {
   test: { type: String, required: true }
  }
};
```
component:
```
import mixin;
export default {
  mixins: [mixin]
};
```

Run storybook and observe the missing props in the prop table

**Expected behavior**
To see the props from the mixin merged appropriately

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: NA

**Comment by pocka** [comment]
@BB101 Which version of the addon are you using? You can show info for mixins only with `storybook-addon-vue-info@1.0.0` (currently in beta) and setting `useDocgen` option to true.

**Comment by pocka** [comment]
Closed due to lack of information
