### ISSUE TITLE
Allow to disable props table

### ISSUE THREAD

**Issue by forforeach** [pocka/storybook-addon-vue-info#77]
**Is your feature request related to a problem? Please describe.**
I try to display a story for a feature, not a single component. Hence `source` and `props` are useless in my case. I can hide the source by setting the `source: false` option. It would be great to have the same option for props table

**Describe the solution you'd like**
`propsTable: false` will allow hiding props table

**Comment by pocka** [comment]
@forforeach You can hide props table with `propsTable: []` (v0.x) or `components: {}` (v1.0) although v0.x  cannot hide `Props` heading. To remove entire props section, please try v1.0 :)
