### ISSUE TITLE
Support for vue-property-decorator

### ISSUE THREAD

**Issue by b0g3r** [pocka/storybook-addon-vue-info#80]
**Is your feature request related to a problem? Please describe.**
I use `vue-property-decorator` and `Prop` decorator, and addon don't generate any content :(

For example:
```ts
import { Prop, Component } from 'vue-property-decorator';
@Component
export default class PublicationListItem extends Vue {
  /**
   * First try
   */
  @Prop({ type: Number })
  /**
   * Oh my
   */
  public id!: number;
```

Is it vue-docgen-api issue?

**Comment by pocka** [comment]
@b0g3r The addon should work well with `vue-property-decorator`. I took a look at your PR refers here then noticed you misses `info` parameter for stories.

```js
.add(
  'story',
  () => ({ template: '<my-component/>' }),
  {
    info: {} // required !!
  }
)
```

**Comment by b0g3r** [comment]
Thanks, [it's working](https://deploy-preview-29--postpost-storybook.netlify.com/?path=/story/publicationlistitem--simple-item) now! 
I think documentation isn't complete about required `info` object

**Comment by pocka** [comment]
NOTE for `info` parameter has added to README (https://github.com/pocka/storybook-addon-vue-info/commit/ea1626627d0155ad25dbf57737e6ef996980a11c)
