### ISSUE TITLE
Story tab will break after switching tab from vue(info)

### ISSUE THREAD

**Issue by goodayue** [pocka/storybook-addon-vue-info#87]
**Describe the bug**
If the description in `vue(info)` is quite long, then it breaks `story` tab. The numbers in `story` tab are not in the correct positions.

**To Reproduce**
- Resize the sidebar smaller to let one line code viewed in two lines
- Switch to `vue(info)` tab then switch back to `story` tab. You will see this issue
- If you refresh the storybook, the issue is gone

**Screenshots**
![Kapture 2019-04-12 at 15 09 57](https://user-images.githubusercontent.com/8426174/56018667-4c85d580-5d35-11e9-8177-a1cf7bc56bb4.gif)

**Versions**

- `storybook-addon-vue-info`: ^1.0.1
- `@storybook/vue`: 5.0.6

**Comment by pocka** [comment]
After a quick investigation, I found [highlight.js CSS](https://github.com/pocka/storybook-addon-vue-info/blob/master/src/components/StorySource/index.vue#L54) suspicious. It overrides `display: flex` styled by storysource addon.

To solve this, we need to inject/eject its CSS manually or apply scope to the component somehow in the addon...

**Comment by pocka** [comment]
Fixed in v1.1.0
