### ISSUE TITLE
Type of prop is required

### ISSUE THREAD

**Issue by grofzero** [pocka/storybook-addon-vue-info#95]
Hi,

We have components with object style props definition, but some of the props doesn't have type defined. In this case extractDocgenInfo.ts breaks with cannot read property of undefined.
Could you please check this issue?

**To Reproduce**
props:{
  value: {
    required:true
  }
}

**Expected behavior**
Allow props with no type

**Versions**

- `storybook-addon-vue-info`: 1.1.1

Thanks in advance,
grofzero

**Comment by pocka** [comment]
@grofzero 
Should we display `any` or keep the table cell blank?
As a TypeScript user, `any` seems to better for me, but I'm not sure for non-TS users...

**Comment by grofzero** [comment]
@pocka

any if fine,

Thank you very much:)

**Comment by pocka** [comment]
Fixed in v1.1.2
